deploy: 
  name: devopswebsite
  env: 
  replicas: 1
  port: 80
  targetport: 80
  image: reptilianusbileciktus/devopswebsite
  tag: latest
  resources:
    enabled: false
    requestCpu: "100Mi"
    requestMemory: "250m"
    limitCpu: "200Mi"
    limitMemory: "500m"
svc:
  enabled: true
  name: devopswebsite
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: fatihayd.in
      paths:
        - path: /
          pathType: Prefix
          serviceName: devopswebsite
          servicePort: 80
  tls:
    - secretName: fatih-tls
      hosts:
        - fatihayd.in
imagePullSecrets:
  - name: docker-hub-secret

