version: 2.1

# Workflows kısmı, iş akışlarını tanımlar
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - push:
          requires:
            - test

# Jobs kısmı, her adımda yapılacak işlemleri tanımlar
jobs:
  # Docker image build işlemi
  build:
    docker:
      - image: cimg/python:3.8  # Python imajını kullanabiliriz, ihtiyacınıza göre değiştirebilirsiniz
    steps:
      - checkout  # Kodunuzu çekin
      - setup_remote_docker:
          version: 20.10.7  # Docker'ın çalışabilmesi için gerekli ortamı sağlıyoruz
          docker_layer_caching: true  # Docker katmanlarını cache ederek daha hızlı build alırız
      - run:
          name: Build Docker Image
          command: |
            docker build -t reptilianusbileciktus/devopswebsite:$CIRCLE_SHA1 .  # Docker image'ı SHA hash ile etiketleyerek oluşturuyoruz
      - run:
          name: Tag Docker Image
          command: |
            docker tag reptilianusbileciktus/devopswebsite:$CIRCLE_SHA1 reptilianusbileciktus/devopswebsite:latest  # Docker imajına "latest" etiketi ekliyoruz
          
  # Docker image üzerinde test işlemi
  test:
    docker:
      - image: cimg/python:3.8  # Test için uygun bir imaj kullanıyoruz (veya ihtiyacınıza göre değiştirebilirsiniz)
    steps:
      - checkout  # Kodunuzu çekin
      - setup_remote_docker:
          version: 20.10.7  # Docker ortamını sağlıyoruz
      - run:
          name: Test Docker Image
          command: |
            docker run --rm reptilianusbileciktus/devopswebsite:$CIRCLE_SHA1 websitetest  # Docker imajınızı çalıştırıp testleri başlatıyoruz

  # Docker image'ı registry'e push etmek
  push:
    docker:
      - image: cimg/python:3.8  # Docker imajını çalıştıracak uygun bir base image kullanıyoruz
    steps:
      - checkout  # Kodunuzu çekin
      - setup_remote_docker:
          version: 20.10.7  # Docker ortamını çalıştırabilmek için gerekli ortamı kuruyoruz
          docker_layer_caching: true
      - run:
          name: Log in to DockerHub
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin  # Docker Hub'a giriş yapıyoruz
      - run:
          name: Push Docker Image
          command: |
            docker push reptilianusbileciktus/devopswebsite:$CIRCLE_SHA1  # Docker imajını registry'e push ediyoruz
            docker push reptilianusbileciktus/devopswebsite:latest  # Latest etiketi ile push ediyoruz
